name: musan_client
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^3.1.5
  firebase_core: 1.11.0
  firebase_messaging: 10.0.9
  firebase_auth: 3.3.5
  get: ^3.26.0
  provider: ^5.0.0
  fluttertoast: ^7.1.1
  smooth_page_indicator: ^0.2.1
  #  custom_switch_button:
  smooth_star_rating: ^1.1.1
  flutter_rating_bar: ^4.0.0
  flutter_datetime_picker: 1.5.1
  intl: ^0.17.0
  dotted_line: ^3.0.0
  image_picker: ^0.7.5
  shared_preferences: ^2.0.5
  google_sign_in: ^5.0.3
  flutter_svg: ^0.22.0
  google_maps_flutter: 2.1.0
  geocoder:
  location:
  pull_to_refresh: ^2.0.0
  flutter_local_notifications: 9.0.2
  url_launcher: ^6.0.6
  webview_flutter: ^2.0.10
  credit_card_validator: ^2.0.0
  flutter_polyline_points: ^1.0.0
  logger: ^1.0.0
  cupertino_icons: ^1.0.2
  geolocator: ^7.0.3
  http:  0.13.4
  dio: ^4.0.4
  signalr_core: ^1.1.1
  shimmer: ^2.0.0
  expandable: ^5.0.1
  android_intent: ^2.0.0
  stack_trace: ^1.10.0
  package_info: ^2.0.0
  map_launcher: ^2.1.1
  flutter_ringtone_player: ^3.1.0
  assets_audio_player: ^3.0.3+6
  flutter_cupertino_datetime_picker: ^3.0.0
  app_tracking_transparency: 2.0.0
  flutter_launcher_icons: ^0.9.2
  sign_in_apple: ^2.0.0
  firebase_analytics: ^9.0.5
  progress_indicators: ^1.0.0
#  flutter_share_me: ^1.2.0
  flutter_email_sender: ^5.1.0
  flutter_share: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: any

flutter_icons:
  android:
  ios:
  remove_alpha_ios: true
  image_path: "assets/logo.png"

  #dependency_overrides:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/audios/
    - assets/home_assets/
    - assets/drawer_icons/
    - assets/invite_screen_assest/
  # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # musan:
  fonts:
    - family: circular
      fonts:
        - asset: assets/fonts/circular.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.

flutter_intl:
  enabled: true
